//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumer
    {
        public int ConsumerId { get; set; }
        public string ConsumerName { get; set; }
        public string ConsumerKey { get; set; }
        public bool IsLocked { get; set; }
    }
}
