//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public long ReviewId { get; set; }
        public long CustomerId { get; set; }
        public double Rating { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int ProductId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
